name: "Javascript Checks"

on:
  pull_request:
    branches:
      - main

    paths:
      - ".github/workflows/javascript-checks.yml"
      - "javascript/**"

jobs:
  Conformity-Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["10"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Checking Code Conformity with Style Guidelines"
        run: |
          cd javascript
          yarn
          yarn lint:check
        env:
          CI: true

  Unit-Tests-Check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: ["10"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Running Tests with Coverage Report"
        run: |
          cd javascript
          yarn
          yarn data
        env:
          CI: true
